name: Build and Push to Docker Hub

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push game image
        uses: docker/build-push-action@v5
        with:
          context: ./clh-game
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clh-game:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/clh-game:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/clh-game:${{ github.ref_name }}

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./clh-server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clh-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/clh-server:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/clh-server:${{ github.ref_name }}
